"""
utils/dummy_data.py — Fake/test data generator for form filling.
All values are obviously fake and safe for any test environment.
"""

import random
import string


def random_string(length: int = 8) -> str:
    return "".join(random.choices(string.ascii_lowercase, k=length))


def get_dummy_email() -> str:
    return f"tester_{random_string(5)}@example.com"


def get_dummy_name() -> str:
    first = ["Test", "Auto", "Demo", "Sample"]
    last  = ["User", "Tester", "Runner", "Agent"]
    return f"{random.choice(first)} {random.choice(last)}"


def get_dummy_phone() -> str:
    return f"98{random.randint(10000000, 99999999)}"


def get_dummy_address() -> str:
    return f"{random.randint(1, 999)} Test Street, Block {random.randint(1,20)}"


DUMMY_MAP = {
    "email":    get_dummy_email,
    "name":     get_dummy_name,
    "phone":    get_dummy_phone,
    "address":  get_dummy_address,
    "city":     lambda: "Test City",
    "zip":      lambda: "110001",
    "username": lambda: f"testuser_{random_string(4)}",
    "search":   lambda: "test search query",
    "message":  lambda: "This is an automated test message generated by Web Auto Tester.",
    "default":  lambda: f"test_{random_string(6)}",
}


def get(key: str = "default") -> str:
    fn = DUMMY_MAP.get(key, DUMMY_MAP["default"])
    return fn()
